project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "Ecological Data Synthesis: A Primer on Essential Methods"
  repo-url: https://github.com/lter/eco-data-synth-primer
  repo-actions: [issue]
  navbar:
    left:
      - text: "Home"
        href: home.qmd
    right:
      - text: "People"
        menu: 
          - text: "Greg Maurer"
            href: https://github.com/gremau
          - text: "Marty Downs"
            href: https://orcid.org/0000-0003-2833-956X
          - text: "Nick Lyon"
            href: https://njlyon0.github.io
      - icon: github
        href: https://github.com/lter/eco-data-synth-primer
        aria-label: GitHub

execute:
  freeze: auto

format:
  html:
    code-overflow: wrap
    code-line-numbers: false
    code-copy: hover
    theme: 
      light: theme_light.scss
      dark: theme_dark.scss
    mainfont: Roboto
    toc: true
    link-external-newwindow: true
    link-external-icon: false
