---
title: "ESA 2025: Ecological data synthesis: a primer on essential methods for team science"
description: "6-hour short course offered at the ESA 2025 annual meeting in Baltimore, MD"
author: "The eco-data-synth team"
date: "2025-08-10"
date-modified: "2026-07-23"
draft: False
---

### Abstract

In recent decades, ecology has become a more collaborative discipline motivated by the search for generality across ecosystems. At the same time,the availability, quantity, and quality of environmental data have grown rapidly, creating opportunities for re-use of these data in ecological synthesis research. Though synthesis research is complex and demanding, taking an inclusive and collaborative approach to both the scientific process and the data pays dividends throughout the lifetime of a project. This short course is a survey of methods for making ecological synthesis research a "team sport". 

**Objectives for learners are to**

1. gain project management and data synthesis skills that are immediately useful in a research team setting,
2. develop an end-to-end (conception to publication) plan for collaborative synthesis research and
3. focus on developing their own synthesis projects, whatever stage they are in, with guidance from instructors and peers.
    
Instructors will cover assembling the team, study design, communication, collecting primary data sources, assembly/harmonization of data, managing analytical workflows, and publication of derived datasets and other synthesis products. The course uses real-world examples, demonstrations, and interactive lessons in small groups. Ecologists with synthesis experience will be on hand with seasoned research advice and data tips.

### Agenda for 2025-08-10

This agenda is subject to change!

| Timing (PT)     |               Content                |
|:---------------:|:------------------------------------:|
| 9:00 - 9:30a    |       Welcome & Introductions        |
| 9:30 - 10:30a   | Module 1: Starting with Team Science |
| 10:30a - 12:00p |   Module 2: Operational Synthesis    |
| 12:00 - 1:00p   |               **Break**              |
| 1:00 - 2:00p    |      ... Module 2, continued ...     |
| 2:00 - 3:00p    |   Module 3: Tying it all together    |
| 3:00 - 4:00p    |   Mentoring session...               |

### Shared notes document

A [**communal notes document**](https://docs.google.com/document/d/1E4fxxZmAIJyUpvdX89FtVcLfU330NTbWT0sdFoJEKME/edit?usp=sharing) will be used during some of the discussions we'll have, and are a good place to drop on-the-fly feedback about the course. Keep the link handy and we'll ask for your input to these notes at key times.

### Introductions & Icebreaker

Before we begin, we'd love to get a sense for who you all are and why you're interested in synthesis work! To that end, we'll take a few minutes and go around the room for introductions. Please include:

- Your name and pronouns
- A 1-sentence summary of your work
- Briefly, _<u>why are you interested in synthesis</u>?_

# Instructors

* Marty Downs
* Jalene Lamontagne
* Nick Lyon
* Greg Maurer
* Eric Sokol

### Code of Conduct

[ESA Code of Conduct](https://esa.org/baltimore2025/code-of-conduct/)

Briefly: Treat all participants with kindness, respect, and consideration, valuing a diversity of views and opinions.
Report unacceptable behavior at (844)-641-4133 or email codeofconduct@esa.org